name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

env:
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/three-tier-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/three-tier-frontend

jobs:
  build:
    name: Build & Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate image tag
        id: tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=sha-${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build & push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          target: production
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.BACKEND_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
            ${{ env.BACKEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          target: production
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.FRONTEND_IMAGE }}:${{ steps.tag.outputs.IMAGE_TAG }}
            ${{ env.FRONTEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Linux VM
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          source: "docker-compose.yml"
          target: "~/three-tier-app/"

      - name: Deploy on VM via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            set -e

            # Install Docker if missing
            if ! command -v docker &>/dev/null; then
              curl -fsSL https://get.docker.com | sh
              sudo usermod -aG docker $USER
            fi

            # Install Docker Compose plugin if missing
            if ! docker compose version &>/dev/null 2>&1; then
              sudo apt-get update -qq && sudo apt-get install -y docker-compose-plugin
            fi

            cd ~/three-tier-app

            # Write .env
            cat > .env <<ENVEOF
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            IMAGE_TAG=sha-${{ github.sha }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            ENVEOF

            # Pull new images and restart
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f

            echo "Deployment complete at $(date)"
